using System;
using System.Collections.Generic;
using UnityEngine;

namespace AgesOfConflict
{
    public enum TerrainType : byte
    {
        DeepOcean = 0,
        ShallowOcean = 1,
        Land = 2
    }

    [System.Serializable]
    public struct Cell
    {
        public byte terrain; // 0 = Deep Ocean, 1 = Shallow Ocean, 2 = Land
        public short nationId; // -1 = Unclaimed, >= 0 = Nation ID

        public bool IsLand => terrain == (byte)TerrainType.Land;
        public bool IsWater => terrain == (byte)TerrainType.DeepOcean || terrain == (byte)TerrainType.ShallowOcean;
        public bool HasOwner => nationId >= 0;
    }

    [System.Serializable]
    public class Nation
    {
        public int id;
        public string name;
        public Color32 color;
        public Vector2Int capital;
        public int territorySize;

        [Header("Economy")]
        public float treasury = 100f;          // Current gold in coffers
        public float incomePerSec = 0f;        // Tax revenue generated by territory
        public float upkeepPerSec = 0f;        // Army maintenance cost per second
        public float netIncomePerSec => incomePerSec - upkeepPerSec;

        [Header("Military (Fixed Low Cap)")]
        public int armyCount = 20;             // Active soldiers
        public int maxArmyTarget = 50;         // Fixed low army cap

        // Active border cells adjacent to unclaimed land
        [System.NonSerialized]
        public List<int> frontier = new List<int>();

        public Nation(int id, string name, Color32 color, Vector2Int capital)
        {
            this.id = id;
            this.name = name;
            this.color = color;
            this.capital = capital;
            this.territorySize = 0;
            this.treasury = 100f;
            this.armyCount = 20;
            this.maxArmyTarget = 50;
            this.frontier = new List<int>();
        }
    }
}
